export enum Types {
 ADD_PASSWORD = 'ADD_PASSWORD',
 REMOVE_PASSWORD = 'REMOVE_PASSWORD',
 SELECT_PASSWORD = 'SELECT_PASSWORD',
 CLEAR_SELECTED_PASSWORD = 'CLEAR_SELECTED_PASSWORD',
 UPDATE_PASSWORD = 'UPDATE_PASSWORD',
 DELETE_SELECTED_PASSWORD = 'DELETE_SELECTED_PASSWORD',
}
