export const ADD_PASSWORD = 'ADD_PASSWORD';
export const REMOVE_PASSWORD = 'REMOVE_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const SELECT_PASSWORD = 'SELECT_PASSWORD';
export const CLEAR_SELECTED_PASSWORD = 'CLEAR_SELECTED_PASSWORD';
export const DELETE_SELECTED_PASSWORD = 'DELETE_SELECTED_PASSWORD';
